name: Tailwings

on:
  workflow_dispatch:
    inputs:
      scale_to:
        description: 'Scale to'
        required: true
        default: '0'
        type: choice
        options:
          - '0'
          - '1 --region=cdg'
          - '1 --region=cph'

jobs:
  scale:
    name: Scale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.3

      - run: flyctl suspend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - run: flyctl scale count ${{ inputs.scale_to }} --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
